run:
  timeout: 1m
  issues-exit-code: 1
  tests: true

linters-settings:
  goimports:
    local-prefixes: github.com/alexeyval/test-task-makves-group
  govet:
    check-shadowing: true
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 2


output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    - dupl
    - deadcode
    - errcheck
    - govet
    - golint
    - gofmt
    - gosimple
    - goconst
    - gosec
    - goimports
    - gocritic
    - gochecknoglobals
    - ineffassign
    - misspell
    - maligned
    - nlreturn
    - prealloc
    - revive
    - staticcheck
    - scopelint
    - typecheck
    - unused
    - unparam
    - varcheck
  fast: false
